name: media-routine Daily

on:
  schedule:
    - cron: '0 19 * * *'  # 日本時間の毎朝4時（UTC 19:00）
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper.py

      - name: Upload scraped results
        uses: actions/upload-artifact@v4
        with:
          name: scraped-files
          path: |
            ./files/

      - name: Upload error log
        uses: actions/upload-artifact@v4
        with:
          name: error-log
          path: error_log.txt
