name: morning-routine-daily

on:
  schedule:
    - cron: '0 19 * * *'  # JST 04:00 実行（UTC 19:00）
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get timestamp in JST
        id: timestamp
        run: |
          TZ=Asia/Tokyo date +'%Y%m%d-%H%M' > time.txt
          echo "time=$(cat time.txt)" >> $GITHUB_OUTPUT

      - name: Run scraper script
        run: python morning-routine.py

      - name: Upload scraped files
        uses: actions/upload-artifact@v4
        with:
          name: scraped-files_${{ steps.timestamp.outputs.time }}
          path: ./files/

      - name: Upload error log (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: error-log
          path: error_log.txt
          if-no-files-found: ignore
